//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX_Database_First
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Purchases = new ObservableCollection<Purchase>();
        }
    
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual ObservableCollection<Purchase> Purchases { get; set; }
    }
}
