//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorksClient
{
    using System;
    
    public enum ShipMethods : int
    {
        XRQ = 1,
        ZY = 2,
        OverSeas = 3,
        OverNight = 4,
        Cargo = 5
    }
}
